namespace Server.Game.Net;

public static class GamePacketId
{
    public enum FromClient
    {
        CLogin,
        CRegister,
        CAddChar,
        CUseChar,
        CDelChar,
        CLogout,
        CSayMsg,
        CBroadcastMsg,
        CPlayerMsg,
        CAdminMsg,
        CPlayerMove,
        CStopPlayerMove,
        CPlayerDir,
        CUseItem,
        CAttack,
        CPlayerInfoRequest,
        CWarpMeTo,
        CWarpToMe,
        CWarpTo,
        CSetSprite,
        CGetStats,
        CRequestNewMap,
        CNeedMap,
        CMapGetItem,
        CMapDropItem,
        CKickPlayer,
        CBanList,
        CBanDestroy,
        CBanPlayer,
        CRequestEditMap,

        CSetAccess,
        CWhosOnline,
        CSetMotd,
        CSearch,
        CSkills,
        CCast,
        CSwapInvSlots,
        CSwapSkillSlots,

        CCheckPing,
        CUnequip,
        CRequestPlayerData,
        CRequestItem,
        CRequestNpc,
        CRequestResource,
        CSpawnItem,
        CTrainStat,

        CRequestAnimation,
        CRequestSkill,
        CRequestShop,
        CRequestLevelUp,
        CForgetSkill,
        CCloseShop,
        CBuyItem,
        CSellItem,
        CChangeBankSlots,
        CDepositItem,
        CWithdrawItem,
        CCloseBank,
        CAdminWarp,
        CTradeInvite,
        CHandleTradeInvite,
        CAcceptTrade,
        CDeclineTrade,
        CTradeItem,
        CUntradeItem,
        CAdmin,
        CSetHotbarSlot,
        CDeleteHotbarSlot,
        CUseHotbarSlot,
        CEventChatReply,
        CEvent,
        CSwitchesAndVariables,
        CRequestSwitchesAndVariables,

        CRequestProjectile,
        CClearProjectile,
        CEmote,
        CRequestParty,
        CAcceptParty,
        CDeclineParty,
        CLeaveParty,
        CPartyChatMsg,

        // *************************
        // ***   EDITOR PACKETS  ***
        // *************************
        CMapRespawn,
        CMapReport,
        CSaveMap,
        CSkillLearn,

        // ####################
        // ### Dev+ Packets ###
        // ####################
        CRequestEditAnimation,
        CSaveAnimation,
        CRequestEditJob,
        CSaveJob,
        CRequestEditItem,
        CSaveItem,
        CRequestEditNpc,
        CSaveNpc,
        CRequestEditProjectile,
        CSaveProjectile,
        CRequestEditResource,
        CSaveResource,
        CRequestEditShop,
        CSaveShop,
        CRequestEditSkill,
        CSaveSkill,

        CRequestMoral,
        CSaveMoral,
        CRequestEditMoral,

        CSaveScript,
        CRequestEditScript,

        CCloseEditor
    }
}