namespace Core.Net;

public static class Packets
{
    public enum ClientPackets
    {
        CLogin = 0,
        CRegister = 1,
        CAddChar = 2,
        CUseChar = 3,
        CDelChar = 4,
        CLogout = 5,
        CSayMsg = 6,
        CBroadcastMsg = 7,
        CPlayerMsg = 8,
        CAdminMsg = 9,
        CPlayerMove = 10,
        CStopPlayerMove = 11,
        CPlayerDir = 12,
        CUseItem = 13,
        CAttack = 14,
        CPlayerInfoRequest = 15,
        CWarpMeTo = 16,
        CWarpToMe = 17,
        CWarpTo = 18,
        CSetSprite = 19,
        CGetStats = 20,
        CRequestNewMap = 21,
        CNeedMap = 22,
        CMapGetItem = 23,
        CMapDropItem = 24,
        CKickPlayer = 25,
        CBanList = 26,
        CBanDestroy = 27,
        CBanPlayer = 28,
        CRequestEditMap = 29,

        CSetAccess = 30,
        CWhosOnline = 31,
        CSetMotd = 32,
        CSearch = 33,
        CSkills = 34,
        CCast = 35,
        CSwapInvSlots = 36,
        CSwapSkillSlots = 37,

        CCheckPing = 38,
        CUnequip = 39,
        CRequestPlayerData = 40,
        CRequestItem = 41,
        CRequestNpc = 42,
        CRequestResource = 43,
        CSpawnItem = 44,
        CTrainStat = 45,

        CRequestAnimation = 46,
        CRequestSkill = 47,
        CRequestShop = 48,
        CRequestLevelUp = 49,
        CForgetSkill = 50,
        CCloseShop = 51,
        CBuyItem = 52,
        CSellItem = 53,
        CChangeBankSlots = 54,
        CDepositItem = 55,
        CWithdrawItem = 56,
        CCloseBank = 57,
        CAdminWarp = 58,
        CTradeInvite = 59,
        CHandleTradeInvite = 60,
        CAcceptTrade = 61,
        CDeclineTrade = 62,
        CTradeItem = 63,
        CUntradeItem = 64,
        CAdmin = 65,
        CSetHotbarSlot = 66,
        CDeleteHotbarSlot = 67,
        CUseHotbarSlot = 68,
        CEventChatReply = 69,
        CEvent = 70,
        CSwitchesAndVariables = 71,
        CRequestSwitchesAndVariables = 72,

        CRequestProjectile = 73,
        CClearProjectile = 74,
        CEmote = 75,
        CRequestParty = 76,
        CAcceptParty = 77,
        CDeclineParty = 78,
        CLeaveParty = 79,
        CPartyChatMsg = 80,

        // *************************
        // ***   EDITOR PACKETS  ***
        // *************************
        CMapRespawn = 81,
        CMapReport = 82,
        CSaveMap = 83,
        CSkillLearn = 84,

        // ####################
        // ### Dev+ Packets ###
        // ####################
        CRequestEditAnimation = 85,
        CSaveAnimation = 86,
        CRequestEditJob = 87,
        CSaveJob = 88,
        CRequestEditItem = 89,
        CSaveItem = 90,
        CRequestEditNpc = 91,
        CSaveNpc = 92,
        CRequestEditProjectile = 93,
        CSaveProjectile = 94,
        CRequestEditResource = 95,
        CSaveResource = 96,
        CRequestEditShop = 97,
        CSaveShop = 98,
        CRequestEditSkill = 99,
        CSaveSkill = 100,

        CRequestMoral = 101,
        CSaveMoral = 102,
        CRequestEditMoral = 103,

        CSaveScript = 104,
        CRequestEditScript = 105,

        CCloseEditor = 106,

        // Make sure COUNT is below everything else
        Count = 107
    }

    public enum ServerPackets
    {
        SAes = 0,
        SAlertMsg = 1,
        SLoginOk = 2,
        SPlayerChars = 3,
        SJobData = 4,
        SInGame = 5,
        SPlayerInv = 6,
        SPlayerInvUpdate = 7,
        SPlayerWornEq = 8,
        SPlayerHp = 9,
        SPlayerMp = 10,
        SPlayerSp = 11,
        SPlayerStats = 12,
        SPlayerData = 13,
        SPlayerMove = 14,
        SNpcMove = 15,
        SPlayerDir = 16,
        SNpcDir = 17,
        SPlayerXy = 18,
        SAttack = 19,
        SNpcAttack = 20,
        SCheckForMap = 21,
        SMapData = 22,
        SMapItemData = 23,
        SMapItemsData = 24,
        SMapNpcData = 25,
        SMapNpcUpdate = 26,
        SGlobalMsg = 27,
        SAdminMsg = 28,
        SPlayerMsg = 29,
        SMapMsg = 30,
        SSpawnItem = 31,
        SItemEditor = 32,
        SUpdateItem = 33,
        SSpawnNpc = 34,
        SNpcDead = 35,
        SNpcEditor = 36,
        SUpdateNpc = 37,
        SEditMap = 38,
        SShopEditor = 39,
        SUpdateShop = 40,
        SSkillEditor = 41,
        SUpdateSkill = 42,
        SSkills = 43,
        SLeftMap = 44,
        SMapResource = 45,
        SResourceEditor = 46,
        SUpdateResource = 47,
        SSendPing = 48,
        SActionMsg = 49,
        SPlayerExp = 50,
        SBlood = 51,
        SAnimationEditor = 52,
        SUpdateAnimation = 53,
        SAnimation = 54,
        SMapNpcVitals = 55,
        SCooldown = 56,
        SClearSkillBuffer = 57,
        SSayMsg = 58,
        SOpenShop = 59,
        SResetShopAction = 60,
        SStunned = 61,
        SMapWornEq = 62,
        SBank = 63,
        SLeftGame = 64,
        STradeInvite = 65,
        STrade = 66,
        SCloseTrade = 67,
        STradeUpdate = 68,
        STradeStatus = 69,
        SMapReport = 70,
        STarget = 71,
        SAdmin = 72,
        SMapNames = 73,
        SCritical = 74,
        SrClick = 75,
        SHotbar = 76,
        SSpawnEvent = 77,
        SEventMove = 78,
        SEventDir = 79,
        SEventChat = 80,
        SEventStart = 81,
        SEventEnd = 82,
        SPlayBgm = 83,
        SPlaySound = 84,
        SFadeoutBgm = 85,
        SStopSound = 86,
        SSwitchesAndVariables = 87,
        SMapEventData = 88,
        SChatBubble = 89,
        SSpecialEffect = 90,
        SPic = 91,
        SHoldPlayer = 92,
        SProjectileEditor = 93,
        SUpdateProjectile = 94,
        SMapProjectile = 95,
        SJobEditor = 96,
        SUpdateJob = 97,
        SUpdateMoral = 98,
        SEmote = 99,
        SPartyInvite = 100,
        SPartyUpdate = 101,
        SPartyVitals = 102,
        SMoralEditor = 103,

        STime = 104,
        SClock = 105,

        SScriptEditor = 106,

        // Make sure COUNT is below everything else
        Count = 107
    }
}