namespace Core.Net;

public static class Packets
{
    public enum ClientPackets
    {
        CLogin = 0,
        CRegister = 1,
        CAddChar = 2,
        CUseChar = 3,
        CDelChar = 4,
        CLogout = 5,
        CSayMsg = 6,
        CBroadcastMsg = 7,
        CPlayerMsg = 8,
        CAdminMsg = 9,
        CPlayerMove = 10,
        CStopPlayerMove = 11,
        CPlayerDir = 12,
        CUseItem = 13,
        CAttack = 14,
        CPlayerInfoRequest = 15,
        CWarpMeTo = 16,
        CWarpToMe = 17,
        CWarpTo = 18,
        CSetSprite = 19,
        CGetStats = 20,
        CRequestNewMap = 21,
        CNeedMap = 22,
        CMapGetItem = 23,
        CMapDropItem = 24,
        CKickPlayer = 25,
        CBanList = 26,
        CBanDestroy = 27,
        CBanPlayer = 28,
        CRequestEditMap = 29,

        CSetAccess = 30,
        CWhosOnline = 31,
        CSetMotd = 32,
        CSearch = 33,
        CSkills = 34,
        CCast = 35,
        CSwapInvSlots = 36,
        CSwapSkillSlots = 37,

        CCheckPing = 38,
        CUnequip = 39,
        CRequestPlayerData = 40,
        CRequestItem = 41,
        CRequestNpc = 42,
        CRequestResource = 43,
        CSpawnItem = 44,
        CTrainStat = 45,

        CRequestAnimation = 46,
        CRequestSkill = 47,
        CRequestShop = 48,
        CRequestLevelUp = 49,
        CForgetSkill = 50,
        CCloseShop = 51,
        CBuyItem = 52,
        CSellItem = 53,
        CChangeBankSlots = 54,
        CDepositItem = 55,
        CWithdrawItem = 56,
        CCloseBank = 57,
        CAdminWarp = 58,
        CTradeInvite = 59,
        CHandleTradeInvite = 60,
        CAcceptTrade = 61,
        CDeclineTrade = 62,
        CTradeItem = 63,
        CUntradeItem = 64,
        CAdmin = 65,
        CSetHotbarSlot = 66,
        CDeleteHotbarSlot = 67,
        CUseHotbarSlot = 68,
        CEventChatReply = 69,
        CEvent = 70,
        CSwitchesAndVariables = 71,
        CRequestSwitchesAndVariables = 72,

        CRequestProjectile = 73,
        CClearProjectile = 74,
        CEmote = 75,
        CRequestParty = 76,
        CAcceptParty = 77,
        CDeclineParty = 78,
        CLeaveParty = 79,
        CPartyChatMsg = 80,

        // *************************
        // ***   EDITOR PACKETS  ***
        // *************************
        CMapRespawn = 81,
        CMapReport = 82,
        CSaveMap = 83,
        CSkillLearn = 84,

        // ####################
        // ### Dev+ Packets ###
        // ####################
        CRequestEditAnimation = 85,
        CSaveAnimation = 86,
        CRequestEditJob = 87,
        CSaveJob = 88,
        CRequestEditItem = 89,
        CSaveItem = 90,
        CRequestEditNpc = 91,
        CSaveNpc = 92,
        CRequestEditProjectile = 93,
        CSaveProjectile = 94,
        CRequestEditResource = 95,
        CSaveResource = 96,
        CRequestEditShop = 97,
        CSaveShop = 98,
        CRequestEditSkill = 99,
        CSaveSkill = 100,

        CRequestMoral = 101,
        CSaveMoral = 102,
        CRequestEditMoral = 103,

        CSaveScript = 104,
        CRequestEditScript = 105,

        CCloseEditor = 106,

        // Make sure COUNT is below everything else
        Count = 107
    }

    public enum ServerPackets
    {
        SAes = 0,
        SAlertMsg = 1,
        SLoginOk = 2,
        SPlayerChars = 3,
        SJobData = 4,
        SInGame = 5,
        SPlayerInv = 6,
        SPlayerInvUpdate = 7,
        SPlayerWornEq = 8,
        SPlayerHp = 9,
        SPlayerMp = 10,
        SPlayerSp = 11,
        SPlayerStats = 12,
        SPlayerData = 13,
        SPlayerMove = 14,
        SNpcMove = 15,
        SPlayerDir = 16,
        SNpcDir = 17,
        SPlayerXy = 18,
        SAttack = 19,
        SNpcAttack = 20,
        SCheckForMap = 21,
        SMapData = 22,
        SMapItemData = 23,
        SMapNpcData = 24,
        SMapNpcUpdate = 25,
        SGlobalMsg = 26,
        SAdminMsg = 27,
        SPlayerMsg = 28,
        SMapMsg = 29,
        SSpawnItem = 30,
        SItemEditor = 31,
        SUpdateItem = 32,
        SSpawnNpc = 33,
        SNpcDead = 34,
        SNpcEditor = 35,
        SUpdateNpc = 36,
        SEditMap = 37,
        SShopEditor = 38,
        SUpdateShop = 39,
        SSkillEditor = 40,
        SUpdateSkill = 41,
        SSkills = 42,
        SLeftMap = 43,
        SMapResource = 44,
        SResourceEditor = 45,
        SUpdateResource = 46,
        SSendPing = 47,
        SActionMsg = 48,
        SPlayerExp = 49,
        SBlood = 50,
        SAnimationEditor = 51,
        SUpdateAnimation = 52,
        SAnimation = 53,
        SMapNpcVitals = 54,
        SCooldown = 55,
        SClearSkillBuffer = 56,
        SSayMsg = 57,
        SOpenShop = 58,
        SResetShopAction = 59,
        SStunned = 60,
        SMapWornEq = 61,
        SBank = 62,
        SLeftGame = 63,
        STradeInvite = 64,
        STrade = 65,
        SCloseTrade = 66,
        STradeUpdate = 67,
        STradeStatus = 68,
        SMapReport = 69,
        STarget = 70,
        SAdmin = 71,
        SMapNames = 72,
        SCritical = 73,
        SrClick = 74,
        SHotbar = 75,
        SSpawnEvent = 76,
        SEventMove = 77,
        SEventDir = 78,
        SEventChat = 79,
        SEventStart = 80,
        SEventEnd = 81,
        SPlayBgm = 82,
        SPlaySound = 83,
        SFadeoutBgm = 84,
        SStopSound = 85,
        SSwitchesAndVariables = 86,
        SMapEventData = 87,
        SChatBubble = 88,
        SSpecialEffect = 89,
        SPic = 90,
        SHoldPlayer = 91,
        SProjectileEditor = 92,
        SUpdateProjectile = 93,
        SMapProjectile = 94,
        SJobEditor = 95,
        SUpdateJob = 96,
        SUpdateMoral = 97,
        SEmote = 98,
        SPartyInvite = 99,
        SPartyUpdate = 100,
        SPartyVitals = 101,
        SMoralEditor = 102,

        STime = 103,
        SClock = 104,

        SScriptEditor = 105,

        // Make sure COUNT is below everything else
        Count = 106
    }
}